version: '3'

networks:
    laravel-media:

services:
    mysql_testing:
        image: mysql/mysql-server:8.0
        container_name: lm-mysql-testing
        tmpfs: /var/lib/mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            MYSQL_ROOT_PASSWORD: laravel
        networks:
            - laravel-media

    php:
        image: owow/laravel-php:8.1
        container_name: lm-php
        tty: true
        volumes:
            - .:/var/www/html:cached
        networks:
            - laravel-media
